gcp_credentials: ENCRYPTED[7ba94e3115455aef552b9863bbd74267aa42f841aa8ddc5f1a836a71ffaa72ec327842b5fe66903c9e3dd1172383f01c]

gke_container:
  image: gcr.io/flutter-cirrus/build-engine-image:latest
  cluster_name: build-32-cluster
  zone: us-central1-a
  namespace: default
  cpu: 30 # can't use all 30-cores; system pods needs cores too
  memory: 100Gb # similarly, can't use all 100Gb memory

build_and_test_host_task:
  container:
    image: gcr.io/flutter-cirrus/build-engine-image:latest
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    GITHUB_TOKEN: ENCRYPTED[da21a18e61acdf856cfc08f28cb8df8323316590188eb1285b96639157b503dfc40576608af62921888c7209794277d0]
  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    mv $CIRRUS_WORKING_DIR flutter
    gclient sync
  compile_host_script: |
    cd $ENGINE_PATH/src
    ./flutter/tools/gn --unoptimized
    ninja -C out/host_debug_unopt    
  test_host_script: cd $ENGINE_PATH/src && ./flutter/testing/run_tests.sh host_debug_unopt

build_android_task:
  container:
    image: gcr.io/flutter-cirrus/build-engine-image:latest
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    GITHUB_TOKEN: ENCRYPTED[da21a18e61acdf856cfc08f28cb8df8323316590188eb1285b96639157b503dfc40576608af62921888c7209794277d0]
  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    mv $CIRRUS_WORKING_DIR flutter
    gclient sync
  android_build_cache:
    folder: out/fly_android_cache
  compile_android_script: |
    cd $ENGINE_PATH/src/flutter
    ./lfkdsk_build_tools/build_android.sh arm release normal

build_ios_task:
  container:
    image: gcr.io/flutter-cirrus/build-engine-image:latest
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    GITHUB_TOKEN: ENCRYPTED[da21a18e61acdf856cfc08f28cb8df8323316590188eb1285b96639157b503dfc40576608af62921888c7209794277d0]
  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    mv $CIRRUS_WORKING_DIR flutter
    gclient sync
  compile_android_script: |
    cd $ENGINE_PATH
    ./src/flutter/lfkdsk_build_tools/ios-gn.sh
    ./src/flutter/lfkdsk_build_tools/ios-ninja.sh
    ./src/flutter/lfkdsk_build_tools/ios-create-framework.sh

format_and_dart_test_task:
  container:
    image: gcr.io/flutter-cirrus/build-engine-image:latest

  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"

  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    cp $CIRRUS_WORKING_DIR -r ./flutter
    gclient sync

  # avoid format check.
  build_script: cd $ENGINE_PATH/src/flutter && ./ci/build.sh
